name: 传参数给 JS

on:
  workflow_dispatch:
    inputs:
      userName:
        description: '你的名字'
        required: true
        default: '张三'
      userAge:
        description: '年龄'
        required: false
        default: '20'

jobs:
  run-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 安装依赖
        run: npm install

      # 重点：把 YML 参数 → 环境变量 → 传给 JS
      - name: 运行 JS 并传参
        run: node index.js
        env:
          # 左边是给JS用的变量名   右边是YML里的参数
          NAME: ${{ inputs.userName }}
          AGE: ${{ inputs.userAge }}
